http:
  routers:
    traefik:
      rule: "Host(`traefik.${host}.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "${host}.localhost"
            sans:
              - "*.${host}.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"