http:
  routers:
    traefik:
      rule: "Host(`traefik.${host}`)"
      service: "api@internal"
      tls:
        domains:
          - main: "${host}"
            sans:
              - "*.${host}"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"